import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import process from 'node:process';

const ROOT = process.cwd();
const SRC = resolve(ROOT, 'src');

interface ModuleEntry {
  readonly name: string;
  readonly path: string;
  readonly exports: readonly string[];
}

const extractExports = (indexPath: string): readonly string[] => {
  if (!existsSync(indexPath)) {
    return [];
  }
  const content = readFileSync(indexPath, 'utf8');
  const names = new Set<string>();
  const patterns = [
    /export\s+(?:type\s+)?\{\s*([^}]+)\s*\}/g,
    /export\s+(?:const|function|class|type|interface|enum)\s+([A-Za-z_$][\w$]*)/g,
  ];
  for (const p of patterns) {
    let m: RegExpExecArray | null;
    while ((m = p.exec(content)) !== null) {
      if (m[1]?.includes(',') || m[1]?.includes(' ')) {
        const names1 = m[1]
          .split(',')
          .map(
            (s) =>
              s
                .trim()
                .replace(/^type\s+/, '')
                .split(/\s+as\s+/)[0],
          )
          .filter(Boolean) as string[];
        for (const n of names1) {
          names.add(n);
        }
      } else if (m[1]) {
        names.add(m[1]);
      }
    }
  }
  return Array.from(names).sort();
};

const walkModules = (root: string): ModuleEntry[] => {
  if (!existsSync(root)) {
    return [];
  }
  const entries = readdirSync(root, { withFileTypes: true });
  const modules: ModuleEntry[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }
    const modulePath = resolve(root, entry.name);
    const indexPath = resolve(modulePath, 'index.ts');
    const exports = extractExports(indexPath);
    if (exports.length > 0) {
      modules.push({
        name: entry.name,
        path: modulePath.replace(`${ROOT}/`, ''),
        exports,
      });
    }
  }
  return modules.sort((a, b) => a.name.localeCompare(b.name));
};

const walkScenes = (): ModuleEntry[] => {
  const base = resolve(SRC, 'runtime', 'phaser', 'scenes');
  return walkModules(base);
};

const listFiles = (dir: string, filter: (name: string) => boolean): string[] => {
  if (!existsSync(dir)) {
    return [];
  }
  return readdirSync(dir)
    .filter(filter)
    .sort()
    .map((f) => `${dir.replace(`${ROOT}/`, '')}/${f}`);
};

const renderTable = (title: string, rows: readonly ModuleEntry[]): string => {
  if (rows.length === 0) {
    return `## ${title}\n\n_(none)_\n`;
  }
  const lines = [`## ${title}`, '', '| Module | Path | Exports |', '|---|---|---|'];
  for (const r of rows) {
    lines.push(
      `| \`${r.name}\` | \`${r.path}\` | ${r.exports.map((e) => `\`${e}\``).join(', ')} |`,
    );
  }
  return `${lines.join('\n')}\n`;
};

const renderFileList = (title: string, files: readonly string[]): string => {
  if (files.length === 0) {
    return `## ${title}\n\n_(none)_\n`;
  }
  return `## ${title}\n\n${files.map((f) => `- \`${f}\``).join('\n')}\n`;
};

const domain = walkModules(resolve(SRC, 'domain'));
const features = walkModules(resolve(SRC, 'features'));
const scenes = walkScenes();

const adapters = listFiles(resolve(SRC, 'runtime', 'adapters'), (f) => f.endsWith('.port.ts'));
const ports = (() => {
  const portsFile = resolve(SRC, 'shared', 'types', 'ports.ts');
  if (!existsSync(portsFile)) {
    return [] as string[];
  }
  const content = readFileSync(portsFile, 'utf8');
  return Array.from(content.matchAll(/export interface (I\w+Port)/g)).map((m) => m[1] as string);
})();
const schemas = listFiles(resolve(SRC, 'content', 'schemas'), (f) => f.endsWith('.schema.ts'));

const generatedAt = new Date().toISOString();

const renderCatalog = (generated: string): string => `# Codebase Catalog

_Auto-generated by \`bun run catalog\`. Do not edit by hand._

Last generated: ${generated}

${renderTable('Domain Modules', domain)}
${renderTable('Features', features)}
${renderTable('Scenes', scenes)}
## Ports (cross-cutting)

${ports.map((p) => `- \`${p}\` — declared in \`src/shared/types/ports.ts\``).join('\n') || '_(none)_'}

${renderFileList('Runtime Adapters', adapters)}
${renderFileList('Content Schemas', schemas)}
`;

const normalizeCatalog = (text: string): string =>
  text.replace(/^Last generated:.*$/m, 'Last generated: <stable>');

const catalogPath = resolve(ROOT, 'docs', 'ai', 'catalog.md');
const out = renderCatalog(generatedAt);

if (process.argv.includes('--check')) {
  if (!existsSync(catalogPath)) {
    console.error(`catalog missing at ${catalogPath}. Run bun run catalog.`);
    process.exit(1);
  }
  const existing = readFileSync(catalogPath, 'utf8');
  if (normalizeCatalog(existing) !== normalizeCatalog(out)) {
    console.error('docs/ai/catalog.md is stale. Run `bun run catalog` and commit the result.');
    process.exit(1);
  }
  console.log('catalog up to date');
  process.exit(0);
}

mkdirSync(resolve(catalogPath, '..'), { recursive: true });
writeFileSync(catalogPath, out, 'utf8');
console.log(`wrote ${catalogPath}`);
